(cl:in-package vectornav-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME-VAL
          TIME
          WEEK-VAL
          WEEK
          UTCTIME-VAL
          UTCTIME
          INSSTATUS-VAL
          INSSTATUS
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          NEDVELX-VAL
          NEDVELX
          NEDVELY-VAL
          NEDVELY
          NEDVELZ-VAL
          NEDVELZ
          ATTUNCERTAINTY-VAL
          ATTUNCERTAINTY
          POSUNCERTAINTY-VAL
          POSUNCERTAINTY
          VELUNCERTAINTY-VAL
          VELUNCERTAINTY
))