# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from erp42mini_driver/erpminiCmdMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class erpminiCmdMsg(genpy.Message):
  _md5sum = "7cd932a7d18e4566ffe6515ef5ba19c0"
  _type = "erp42mini_driver/erpminiCmdMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool dir
int16 speed
int16 steer
int16 brake
bool encoder_reset"""
  __slots__ = ['dir','speed','steer','brake','encoder_reset']
  _slot_types = ['bool','int16','int16','int16','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dir,speed,steer,brake,encoder_reset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(erpminiCmdMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.dir is None:
        self.dir = False
      if self.speed is None:
        self.speed = 0
      if self.steer is None:
        self.steer = 0
      if self.brake is None:
        self.brake = 0
      if self.encoder_reset is None:
        self.encoder_reset = False
    else:
      self.dir = False
      self.speed = 0
      self.steer = 0
      self.brake = 0
      self.encoder_reset = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3hB().pack(_x.dir, _x.speed, _x.steer, _x.brake, _x.encoder_reset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.dir, _x.speed, _x.steer, _x.brake, _x.encoder_reset,) = _get_struct_B3hB().unpack(str[start:end])
      self.dir = bool(self.dir)
      self.encoder_reset = bool(self.encoder_reset)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3hB().pack(_x.dir, _x.speed, _x.steer, _x.brake, _x.encoder_reset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.dir, _x.speed, _x.steer, _x.brake, _x.encoder_reset,) = _get_struct_B3hB().unpack(str[start:end])
      self.dir = bool(self.dir)
      self.encoder_reset = bool(self.encoder_reset)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3hB = None
def _get_struct_B3hB():
    global _struct_B3hB
    if _struct_B3hB is None:
        _struct_B3hB = struct.Struct("<B3hB")
    return _struct_B3hB
