# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nmea_msgs/Gpgst.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Gpgst(genpy.Message):
  _md5sum = "e4b77f6f4c211629ab0307177f71dcee"
  _type = "nmea_msgs/Gpgst"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Message from GPGST NMEA String
Header header

string message_id

# UTC seconds from midnight
float64 utc_seconds

# Root-Mean-Squared value of standard deviation of range inputs
float32 rms

# Standard Deviations of semi-major and minor axes of error ellipse
float32 semi_major_dev
float32 semi_minor_dev

# Orientation of the semi-major axis of error ellipse with respect to true north
float32 orientation

# Standard Deviations of latitude, longitude, and altitude measurements
float32 lat_dev
float32 lon_dev
float32 alt_dev

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','message_id','utc_seconds','rms','semi_major_dev','semi_minor_dev','orientation','lat_dev','lon_dev','alt_dev']
  _slot_types = ['std_msgs/Header','string','float64','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,message_id,utc_seconds,rms,semi_major_dev,semi_minor_dev,orientation,lat_dev,lon_dev,alt_dev

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Gpgst, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.message_id is None:
        self.message_id = ''
      if self.utc_seconds is None:
        self.utc_seconds = 0.
      if self.rms is None:
        self.rms = 0.
      if self.semi_major_dev is None:
        self.semi_major_dev = 0.
      if self.semi_minor_dev is None:
        self.semi_minor_dev = 0.
      if self.orientation is None:
        self.orientation = 0.
      if self.lat_dev is None:
        self.lat_dev = 0.
      if self.lon_dev is None:
        self.lon_dev = 0.
      if self.alt_dev is None:
        self.alt_dev = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.message_id = ''
      self.utc_seconds = 0.
      self.rms = 0.
      self.semi_major_dev = 0.
      self.semi_minor_dev = 0.
      self.orientation = 0.
      self.lat_dev = 0.
      self.lon_dev = 0.
      self.alt_dev = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.message_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d7f().pack(_x.utc_seconds, _x.rms, _x.semi_major_dev, _x.semi_minor_dev, _x.orientation, _x.lat_dev, _x.lon_dev, _x.alt_dev))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.utc_seconds, _x.rms, _x.semi_major_dev, _x.semi_minor_dev, _x.orientation, _x.lat_dev, _x.lon_dev, _x.alt_dev,) = _get_struct_d7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.message_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d7f().pack(_x.utc_seconds, _x.rms, _x.semi_major_dev, _x.semi_minor_dev, _x.orientation, _x.lat_dev, _x.lon_dev, _x.alt_dev))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.message_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.message_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.utc_seconds, _x.rms, _x.semi_major_dev, _x.semi_minor_dev, _x.orientation, _x.lat_dev, _x.lon_dev, _x.alt_dev,) = _get_struct_d7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_d7f = None
def _get_struct_d7f():
    global _struct_d7f
    if _struct_d7f is None:
        _struct_d7f = struct.Struct("<d7f")
    return _struct_d7f
