# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from erp_driver/erpStatusMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class erpStatusMsg(genpy.Message):
  _md5sum = "c9878ccc909e763ca6b607c34a8914ba"
  _type = "erp_driver/erpStatusMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 control_mode
bool e_stop
uint8 gear
uint8 speed
int32 steer
uint8 brake
int32 encoder
uint8 alive"""
  __slots__ = ['control_mode','e_stop','gear','speed','steer','brake','encoder','alive']
  _slot_types = ['int8','bool','uint8','uint8','int32','uint8','int32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       control_mode,e_stop,gear,speed,steer,brake,encoder,alive

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(erpStatusMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.control_mode is None:
        self.control_mode = 0
      if self.e_stop is None:
        self.e_stop = False
      if self.gear is None:
        self.gear = 0
      if self.speed is None:
        self.speed = 0
      if self.steer is None:
        self.steer = 0
      if self.brake is None:
        self.brake = 0
      if self.encoder is None:
        self.encoder = 0
      if self.alive is None:
        self.alive = 0
    else:
      self.control_mode = 0
      self.e_stop = False
      self.gear = 0
      self.speed = 0
      self.steer = 0
      self.brake = 0
      self.encoder = 0
      self.alive = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b3BiBiB().pack(_x.control_mode, _x.e_stop, _x.gear, _x.speed, _x.steer, _x.brake, _x.encoder, _x.alive))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.control_mode, _x.e_stop, _x.gear, _x.speed, _x.steer, _x.brake, _x.encoder, _x.alive,) = _get_struct_b3BiBiB().unpack(str[start:end])
      self.e_stop = bool(self.e_stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b3BiBiB().pack(_x.control_mode, _x.e_stop, _x.gear, _x.speed, _x.steer, _x.brake, _x.encoder, _x.alive))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.control_mode, _x.e_stop, _x.gear, _x.speed, _x.steer, _x.brake, _x.encoder, _x.alive,) = _get_struct_b3BiBiB().unpack(str[start:end])
      self.e_stop = bool(self.e_stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b3BiBiB = None
def _get_struct_b3BiBiB():
    global _struct_b3BiBiB
    if _struct_b3BiBiB is None:
        _struct_b3BiBiB = struct.Struct("<b3BiBiB")
    return _struct_b3BiBiB
